name: Practice Control 
on: push
jobs:
  job1:
    strategy:
      matrix:
        node-version: [14, 16]
        print-val: [1, 2]
    runs-on: ${{matrix.node-version}}
    steps:
      - name: fail test
        continue-on-error: true
        id: fail-test
        run: exit 1
      - name: run test even if fail
        if: always() 
        run: |
          echo "This step will run even if the previous step fails"
          echo "Step ID: ${{ steps.fail-test.id }}"
          echo "Step Status: ${{ steps.fail-test.outcome }}"
          echo "Step Conclusion: ${{ steps.fail-test.conclusion }}"
          echo "${{matrix.print-val}}"